export type DiscoverPage = {
  pageName: string;
  niche: string;
  followerCount: string;
  piqScore: number;
  engagementRate: string;
  searchQuery: string;
};

export type DiscoverCategory = {
  id: string;
  name: string;
  pages: DiscoverPage[];
};

export const discoverCategories: DiscoverCategory[] = [
  {
    id: "sports",
    name: "Sports",
    pages: [
      {
        pageName: "ESPN",
        niche: "Sports media & highlights",
        followerCount: "45.2M",
        piqScore: 91,
        engagementRate: "3.2%",
        searchQuery: "ESPN",
      },
      {
        pageName: "NBA",
        niche: "Professional basketball",
        followerCount: "42.8M",
        piqScore: 89,
        engagementRate: "2.8%",
        searchQuery: "NBA",
      },
      {
        pageName: "Bleacher Report",
        niche: "Sports culture & viral clips",
        followerCount: "8.4M",
        piqScore: 84,
        engagementRate: "4.1%",
        searchQuery: "Bleacher Report",
      },
      {
        pageName: "FC Barcelona",
        niche: "Global football club",
        followerCount: "115M",
        piqScore: 92,
        engagementRate: "2.1%",
        searchQuery: "fcbarcelona",
      },
      {
        pageName: "Olympics",
        niche: "International sports events",
        followerCount: "19.6M",
        piqScore: 86,
        engagementRate: "3.5%",
        searchQuery: "Olympics",
      },
    ],
  },
  {
    id: "news",
    name: "News",
    pages: [
      {
        pageName: "CNN",
        niche: "Breaking news & politics",
        followerCount: "32.1M",
        piqScore: 88,
        engagementRate: "1.9%",
        searchQuery: "CNN",
      },
      {
        pageName: "BBC News",
        niche: "Global news coverage",
        followerCount: "58.3M",
        piqScore: 90,
        engagementRate: "1.6%",
        searchQuery: "BBC News",
      },
      {
        pageName: "The New York Times",
        niche: "Investigative journalism",
        followerCount: "18.7M",
        piqScore: 85,
        engagementRate: "2.2%",
        searchQuery: "nytimes",
      },
      {
        pageName: "Reuters",
        niche: "Wire & business news",
        followerCount: "12.4M",
        piqScore: 82,
        engagementRate: "1.4%",
        searchQuery: "Reuters",
      },
      {
        pageName: "Al Jazeera English",
        niche: "International affairs",
        followerCount: "14.2M",
        piqScore: 83,
        engagementRate: "2.0%",
        searchQuery: "Al Jazeera English",
      },
      {
        pageName: "NPR",
        niche: "Public radio & culture",
        followerCount: "7.8M",
        piqScore: 81,
        engagementRate: "2.8%",
        searchQuery: "NPR",
      },
    ],
  },
  {
    id: "entertainment",
    name: "Entertainment",
    pages: [
      {
        pageName: "Netflix",
        niche: "Streaming & originals",
        followerCount: "92.5M",
        piqScore: 93,
        engagementRate: "2.4%",
        searchQuery: "Netflix",
      },
      {
        pageName: "Disney",
        niche: "Family entertainment",
        followerCount: "38.9M",
        piqScore: 87,
        engagementRate: "2.9%",
        searchQuery: "Disney",
      },
      {
        pageName: "MTV",
        niche: "Music & pop culture",
        followerCount: "11.2M",
        piqScore: 79,
        engagementRate: "3.6%",
        searchQuery: "MTV",
      },
      {
        pageName: "BuzzFeed",
        niche: "Viral lists & quizzes",
        followerCount: "9.6M",
        piqScore: 78,
        engagementRate: "4.8%",
        searchQuery: "BuzzFeed",
      },
      {
        pageName: "WWE",
        niche: "Pro wrestling entertainment",
        followerCount: "62.1M",
        piqScore: 88,
        engagementRate: "3.1%",
        searchQuery: "WWE",
      },
    ],
  },
  {
    id: "business",
    name: "Business",
    pages: [
      {
        pageName: "Forbes",
        niche: "Business leaders & wealth",
        followerCount: "6.2M",
        piqScore: 84,
        engagementRate: "2.3%",
        searchQuery: "Forbes",
      },
      {
        pageName: "Harvard Business Review",
        niche: "Management & strategy",
        followerCount: "5.4M",
        piqScore: 86,
        engagementRate: "2.7%",
        searchQuery: "Harvard Business Review",
      },
      {
        pageName: "CNBC",
        niche: "Markets & finance news",
        followerCount: "4.8M",
        piqScore: 83,
        engagementRate: "1.8%",
        searchQuery: "CNBC",
      },
      {
        pageName: "Shopify",
        niche: "E-commerce & entrepreneurship",
        followerCount: "3.9M",
        piqScore: 85,
        engagementRate: "3.4%",
        searchQuery: "Shopify",
      },
      {
        pageName: "Gary Vaynerchuk",
        niche: "Entrepreneurship & marketing",
        followerCount: "4.1M",
        piqScore: 82,
        engagementRate: "4.2%",
        searchQuery: "gary",
      },
      {
        pageName: "Inc. Magazine",
        niche: "Startups & growth",
        followerCount: "2.7M",
        piqScore: 80,
        engagementRate: "2.5%",
        searchQuery: "Inc",
      },
    ],
  },
  {
    id: "food",
    name: "Food",
    pages: [
      {
        pageName: "Tasty",
        niche: "Quick recipe videos",
        followerCount: "98.7M",
        piqScore: 94,
        engagementRate: "5.1%",
        searchQuery: "tasty",
      },
      {
        pageName: "Bon Appétit",
        niche: "Gourmet cooking",
        followerCount: "4.3M",
        piqScore: 83,
        engagementRate: "3.8%",
        searchQuery: "bonappetitmag",
      },
      {
        pageName: "Food Network",
        niche: "TV chefs & recipes",
        followerCount: "28.5M",
        piqScore: 87,
        engagementRate: "2.6%",
        searchQuery: "Food Network",
      },
      {
        pageName: "Gordon Ramsay",
        niche: "Celebrity chef",
        followerCount: "22.1M",
        piqScore: 89,
        engagementRate: "3.9%",
        searchQuery: "Gordon Ramsay",
      },
      {
        pageName: "Delish",
        niche: "Comfort food & trends",
        followerCount: "12.8M",
        piqScore: 85,
        engagementRate: "4.4%",
        searchQuery: "delish",
      },
    ],
  },
  {
    id: "travel",
    name: "Travel",
    pages: [
      {
        pageName: "Lonely Planet",
        niche: "Destination guides",
        followerCount: "3.2M",
        piqScore: 81,
        engagementRate: "3.1%",
        searchQuery: "lonelyplanet",
      },
      {
        pageName: "National Geographic Travel",
        niche: "Adventure & photography",
        followerCount: "28.4M",
        piqScore: 90,
        engagementRate: "2.5%",
        searchQuery: "NatGeoTravel",
      },
      {
        pageName: "Airbnb",
        niche: "Vacation rentals",
        followerCount: "15.6M",
        piqScore: 88,
        engagementRate: "2.2%",
        searchQuery: "Airbnb",
      },
      {
        pageName: "Expedia",
        niche: "Travel deals & booking",
        followerCount: "8.9M",
        piqScore: 79,
        engagementRate: "1.7%",
        searchQuery: "Expedia",
      },
      {
        pageName: "Travel + Leisure",
        niche: "Luxury & lifestyle travel",
        followerCount: "5.1M",
        piqScore: 82,
        engagementRate: "2.9%",
        searchQuery: "Travel Leisure",
      },
      {
        pageName: "Hostelworld",
        niche: "Budget backpacking",
        followerCount: "2.4M",
        piqScore: 77,
        engagementRate: "3.6%",
        searchQuery: "Hostelworld",
      },
    ],
  },
  {
    id: "technology",
    name: "Technology",
    pages: [
      {
        pageName: "Apple",
        niche: "Consumer electronics",
        followerCount: "14.2M",
        piqScore: 91,
        engagementRate: "1.8%",
        searchQuery: "Apple",
      },
      {
        pageName: "The Verge",
        niche: "Tech news & reviews",
        followerCount: "3.8M",
        piqScore: 84,
        engagementRate: "3.2%",
        searchQuery: "verge",
      },
      {
        pageName: "WIRED",
        niche: "Science & future tech",
        followerCount: "4.6M",
        piqScore: 85,
        engagementRate: "2.4%",
        searchQuery: "WIRED",
      },
      {
        pageName: "NVIDIA",
        niche: "GPUs & AI hardware",
        followerCount: "2.9M",
        piqScore: 88,
        engagementRate: "3.7%",
        searchQuery: "NVIDIA",
      },
      {
        pageName: "Microsoft",
        niche: "Software & cloud",
        followerCount: "9.1M",
        piqScore: 86,
        engagementRate: "2.1%",
        searchQuery: "Microsoft",
      },
    ],
  },
  {
    id: "fashion",
    name: "Fashion",
    pages: [
      {
        pageName: "Vogue",
        niche: "High fashion & runway",
        followerCount: "9.8M",
        piqScore: 87,
        engagementRate: "2.3%",
        searchQuery: "Vogue",
      },
      {
        pageName: "Zara",
        niche: "Fast fashion retail",
        followerCount: "31.2M",
        piqScore: 89,
        engagementRate: "1.5%",
        searchQuery: "Zara",
      },
      {
        pageName: "Nike",
        niche: "Athletic lifestyle",
        followerCount: "39.5M",
        piqScore: 92,
        engagementRate: "2.0%",
        searchQuery: "nike",
      },
      {
        pageName: "H&M",
        niche: "Affordable trends",
        followerCount: "42.7M",
        piqScore: 84,
        engagementRate: "1.2%",
        searchQuery: "hm",
      },
      {
        pageName: "GQ",
        niche: "Men's style & culture",
        followerCount: "4.5M",
        piqScore: 83,
        engagementRate: "2.8%",
        searchQuery: "GQ",
      },
      {
        pageName: "Sephora",
        niche: "Beauty & cosmetics",
        followerCount: "21.3M",
        piqScore: 88,
        engagementRate: "2.6%",
        searchQuery: "Sephora",
      },
    ],
  },
];
